apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: configure-node
  namespace: windows-nodepool
spec:
  selector:
    matchLabels:
      name: configure-node
  template:
    metadata:
      labels:
        name: configure-node
    spec:
      hostNetwork: true
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: configure-node
          # this image does not work in win server 2019 nodepools
          image: mcr.microsoft.com/powershell
          command:
            # For NVidia T4 machines, install grid driver - Restart is triggered automatically after install
            - powershell
            - /c
            - $currentVersion=$(containerd --version);
            - $version="1.7.0-beta.3";
            - echo "$version";
            - echo "$currentVersion";
            - if ($currentVersion -like "*$version*") { while ($true) { Start-Sleep 30 }};
            - echo "Install '$version' version of containerd";
            - curl.exe  -o containerd-windows-amd64.tar.gz -L https://github.com/containerd/containerd/releases/download/v$version/containerd-$version-windows-amd64.tar.gz;
            - tar.exe xvf .\containerd-windows-amd64.tar.gz;
            - Copy-Item -Path ".\bin\ctr.exe" -Destination "$Env:ProgramFiles\containerd" -Force;
            - Copy-Item -Path ".\bin\containerd-shim-runhcs-v1.exe" -Destination "$Env:ProgramFiles\containerd" -Force;
            - Copy-Item -Path ".\bin\containerd.exe" -Destination "$Env:ProgramFiles\containerd" -Force;
            - echo "Install NVIDIA GRID driver";
            - curl.exe -L -o nvidia_grid.exe https://download.microsoft.com/download/7/3/6/7361d1b9-08c8-4571-87aa-18cf671e71a0/512.78_grid_win10_win11_server2016_server2019_server2022_64bit_azure_swl.exe;
            - Start-Process -FilePath nvidia_grid.exe -Wait -ArgumentList '-s';
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
